name: 'Workflow Event'

description: 'Parses workflow events'

inputs:
  github-token:
    description: "GitHub token. (e.g. secrets.GITHUB_TOKEN)"
    required: true

outputs:
  ref:
    description: "Event's commit ref"
  sha:
    description: "Event's commit sha"
  commit:
    description: "Event's commit message"

runs:
  using: 'node12'
  main: 'dist/index.js'
